<a href="https://colab.research.google.com/github/Alecia113/self-directed-exercises-python-/blob/NLP/nlp_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch**

**Tensor张量**

In [ ]:
#Tensor 张量 computation graph + automatic differentiation \计算图和自动微分
'''
nerual networks
  nd-tensor instance \调用 nd——》n dimensional
attributes
  1:rank 等级 dimensions numbers(维数):rank-2 tensor == 2d-tensor
  2：Axes 轴 specific demensions(特定尺寸) Axes == dimensions(number) 轴数等于尺寸数（维度数）
              axes length == how number elements running along this axis (轴长＝沿该轴延伸的元素数)
  3： shape 形状 axis length (formed) [由每个轴的长度形成]
              eg:shape(1,2)== 2d-tensor :first axis = 1(length) second axis = 2 [2d张量，第一轴长度1，第二轴长度2]
              scalar(标量); vector(向量) ;matrix（矩阵）;cube（立方骰子）
 【代码】key properties 关键属性
    torch.dtype: torch.float32（数据类型）
    torch.device:CPU/CUDA(GPU)\(一个对象在其上；或将要分配的torch.Tensor的设备【火炬张量】)
    torch.layout: memory layout (torch.Tensor 内存布局对象)
  
              '''


**Computational graph and automatic differentiation 计算图和自动微分**

In [ ]:
'''
  （有向无环 directed acyclic) 计算图 computational graphs to draw some doing functional about tensors in neural networks
  PyTorch使用（有向无环）计算图来绘制应用于神经网络内部张量的功能操作，从而计算出用于网络优化的导数
   use in net optimization : by  calculate derivatives 
In graphs (🐰)
  nodes == tensors
  eages == functions: + * [ output tensors from input tensors(入到出函数 求和×)]
  computational graph == dynamic computational graph
  当在神经网络的前向传递过程中创建操作时，PyTorch会即时生成计算图，称为动态计算图
  '''

# **programming**

**importing PyTorch library**[beginning]


In [1]:
import torch 
print(torch.__version__)

1.7.1+cu101


**create tensors ~~numerical data (数值数据）**

数scalar

In [4]:
import numpy as np

data = torch.tensor(1)# scalar (0 rank)[0demensions]
print(data.shape)

torch.Size([])


In [5]:
data#tensor(1)

tensor(1)

向量

In [6]:
data = np.array([1,2]) # Vector (1 rank~~~1 demensions)
data = torch.Tensor(data)
print(data.shape)

torch.Size([2])


In [7]:
data #tensor([1., 2.])

tensor([1., 2.])

Tensor he tensor 测试

In [8]:
data = np.array([1,2])
data = torch.tensor(data)#大小写
print(data.shape)

torch.Size([2])


In [9]:
data#tensor([1, 2])

tensor([1, 2])

矩阵 matrx

In [10]:
data = np.ones((2,2,))# matrix (2rank) 2D 注意括号
data = torch.Tensor(data) #大写
print(data.shape)

torch.Size([2, 2])


In [11]:
data
'''tensor([[1., 1.],
          [1., 1.]])
        '''

tensor([[1., 1.],
        [1., 1.]])

块：cube

In [13]:
data = np.ones((2,2,2))# Cube (3 rank = 3D 括号)
data = torch.Tensor(data)#还得让张量跑一下
print(data.shape)

torch.Size([2, 2, 2])


In [14]:
data
'''
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
         '''

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

块向量

In [16]:
data = np.ones((2,2,2,2,))#都是one  vector of cubes  4rank 4d
data = torch.Tensor(data)
print(data.shape)

torch.Size([2, 2, 2, 2])


In [17]:
data #有点像国王下棋盘那种feel
'''
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
          '''

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#注意1：大小写的t、、2：T: constructor ( bulid function)   t: factory function(construct+return to caller)
'''
t: 它不仅构造了torch.Tensor 还反馈了他们给调用者
T： can return empty tensor don't use input special data but t : must input data

'''

In [21]:
data = torch.Tensor()#一个数就不需要ones了大于3都需要2 是array
print(data)

tensor([])


In [ ]:
'''data = torch.tensor()
print(data)
'''
#TypeError: tensor() missing 1 required positional arguments: "data"

数据类型

In [ ]:
'''
  torch.Tensor default dtype "float32" 
  torch.tensor() dtype == input data dtype #传入的数据（类型推断）
  example
  '''