<a href="https://colab.research.google.com/github/Alecia113/self-directed-exercises-python-/blob/NLP/nlp_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch**

**Tensor张量**

In [ ]:
#Tensor 张量 computation graph + automatic differentiation \计算图和自动微分
'''
nerual networks
  nd-tensor instance \调用 nd——》n dimensional
attributes
  1:rank 等级 dimensions numbers(维数):rank-2 tensor == 2d-tensor
  2：Axes 轴 specific demensions(特定尺寸) Axes == dimensions(number) 轴数等于尺寸数（维度数）
              axes length == how number elements running along this axis (轴长＝沿该轴延伸的元素数)
  3： shape 形状 axis length (formed) [由每个轴的长度形成]
              eg:shape(1,2)== 2d-tensor :first axis = 1(length) second axis = 2 [2d张量，第一轴长度1，第二轴长度2]
              scalar(标量); vector(向量) ;matrix（矩阵）;cube（立方骰子）
 【代码】key properties 关键属性
    torch.dtype: torch.float32（数据类型）
    torch.device:CPU/CUDA(GPU)\(一个对象在其上；或将要分配的torch.Tensor的设备【火炬张量】)
    torch.layout: memory layout (torch.Tensor 内存布局对象)
  
              '''


**Computational graph and automatic differentiation 计算图和自动微分**

In [ ]:
'''
  （有向无环 directed acyclic) 计算图 computational graphs to draw some doing functional about tensors in neural networks
  PyTorch使用（有向无环）计算图来绘制应用于神经网络内部张量的功能操作，从而计算出用于网络优化的导数
   use in net optimization : by  calculate derivatives 
In graphs (🐰)
  nodes == tensors
  eages == functions: + * [ output tensors from input tensors(入到出函数 求和×)]
  computational graph == dynamic computational graph
  当在神经网络的前向传递过程中创建操作时，PyTorch会即时生成计算图，称为动态计算图
  '''

# **programming**

**importing PyTorch library**[beginning]


In [35]:
import torch 
print(torch.__version__)

1.7.1+cu101


**create tensors ~~numerical data (数值数据）**

数scalar

In [36]:
import numpy as np

data = torch.tensor(1)# scalar (0 rank)[0demensions]
print(data.shape)

torch.Size([])


In [3]:
data#tensor(1)

tensor(1)

向量

In [ ]:
data = np.array([1,2]) # Vector (1 rank~~~1 demensions)
data = torch.Tensor(data)
print(data.shape)

torch.Size([2])


In [ ]:
data #tensor([1., 2.])

tensor([1., 2.])

Tensor he tensor 测试

In [ ]:
data = np.array([1,2])
data = torch.tensor(data)#大小写
print(data.shape)

torch.Size([2])


In [ ]:
data#tensor([1, 2])

tensor([1, 2])

矩阵 matrx

In [ ]:
data = np.ones((2,2,))# matrix (2rank) 2D 注意括号
data = torch.Tensor(data) #大写
print(data.shape)

torch.Size([2, 2])


In [ ]:
data
'''tensor([[1., 1.],
          [1., 1.]])
        '''

tensor([[1., 1.],
        [1., 1.]])

块：cube

In [ ]:
data = np.ones((2,2,2))# Cube (3 rank = 3D 括号)
data = torch.Tensor(data)#还得让张量跑一下
print(data.shape)

torch.Size([2, 2, 2])


In [ ]:
data
'''
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
         '''

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

块向量

In [ ]:
data = np.ones((2,2,2,2,))#都是one  vector of cubes  4rank 4d
data = torch.Tensor(data)
print(data.shape)

torch.Size([2, 2, 2, 2])


In [ ]:
data #有点像国王下棋盘那种feel
'''
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
          '''

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#注意1：大小写的t、、2：T: constructor ( bulid function)   t: factory function(construct+return to caller)
'''
t: 它不仅构造了torch.Tensor 还反馈了他们给调用者
T： can return empty tensor don't use input special data but t : must input data

'''

In [ ]:
data = torch.Tensor()#一个数就不需要ones了大于3都需要2 是array
print(data)

tensor([])


In [ ]:
'''data = torch.tensor()
print(data)
'''
#TypeError: tensor() missing 1 required positional arguments: "data"

数据类型

In [ ]:
'''
  torch.Tensor default dtype "float32" 
  torch.tensor() dtype == input data dtype #传入的数据（类型推断）
  example
  '''

In [5]:
data = np.array([1,2]) #数组int64
print(data.dtype)

int64


In [6]:
data_T = torch.Tensor(data)  #是之前传入的
print(data_T)

tensor([1., 2.])


In [7]:
print(data_T.dtype) #默认是float32

torch.float32


In [8]:
print(data_T.dtype== torch.get_default_dtype())# default 默认 

True


In [9]:
print()

In [ ]:
# change use 'torch.set_default_dtype(dtype)

In [10]:
data_t = torch.tensor(data)

In [11]:
data_t

tensor([1, 2])

In [12]:
print(data_t)

tensor([1, 2])


In [13]:
print(data_t.dtype)

torch.int64


In [19]:
#specify datatype (指定) 'torch.tensor()
data_t = torch.tensor(data, dtype=torch.float64)#(tensou) 就是在后面多加个参数

In [20]:
data_t.dtype

torch.float64

In [21]:
data_t

tensor([1., 2.], dtype=torch.float64)

In [22]:
#期望expect 使用torch.Tensor + torch.tensor  or // torch.as_tensor  + torch.from_numpy

In [23]:
#创建张量tensor 'torch.as_tensor'
data = np.ones((2,2,2))

In [24]:
data

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
data = torch.as_tensor(data)

In [26]:
data

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], dtype=torch.float64)

In [27]:
print(data.shape)

torch.Size([2, 2, 2])


In [39]:
# 创建张量 create tensor 'torch.form_numpy
data = np.ones((2,2,2,2))

In [40]:
data

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [41]:
data = torch.from_numpy(data) #from form  
'''为啥要建张量？'''

In [42]:
data

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]], dtype=torch.float64)

In [43]:
print(data.shape)

torch.Size([2, 2, 2, 2])


factory functions  to create tensors without data

In [46]:
torch.eye(2)  #单位矩阵 identity matrix

tensor([[1., 0.],
        [0., 1.]])

In [47]:
torch.zeros(2,2)# all zeros

tensor([[0., 0.],
        [0., 0.]])

In [48]:
torch.zeros(2,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [49]:
torch.ones(2,2)# 返回给定形状的张量。并填满 given shape filled with all ones

tensor([[1., 1.],
        [1., 1.]])

In [50]:
torch.ones(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [54]:
torch.ones(4)#行

tensor([1., 1., 1., 1.])

In [51]:
torch.ones(4,4)#1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
torch.ones(4,4,4)#4

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [53]:
torch.ones(4,4,4,4)  #16

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],


In [55]:
torch.rand(2)#given shap____values fill it  uniform distribution 均匀分布 on[0,1)

tensor([0.6223, 0.8618])

In [56]:
torch.rand(2)

tensor([0.7719, 0.1198])

In [57]:
torch.rand(2,2) 

tensor([[0.6878, 0.1390],
        [0.4860, 0.7395]])

In [58]:
torch.rand(2,2,2)

tensor([[[0.9508, 0.8656],
         [0.3788, 0.8393]],

        [[0.6918, 0.4496],
         [0.5283, 0.5645]]])

**basic tensor operations 基本张量计算**

In [ ]:
#https://pytorch.org/docs/stable/torch.html#math-operations


simple linear regression algorithm

prepare data 准备数据

In [59]:
import numpy
import matplotlib.pyplot as plt
import torch

In [64]:
#training data
x_training = numpy.asarray([1,2,5,8,9,12,14,16,18,20])
y_training = numpy.asarray([1500,3500,7200,11000,12500,18500,22000,24500,28000,30500])

x_test = numpy.asarray([3,7,13,15,19])
y_test = numpy.asarray([4400,10000,19500,23500,29000])


In [65]:
#create tensor : training
x_data = torch.from_numpy(x_training)

In [66]:
x_data#就是输出出来了

tensor([ 1,  2,  5,  8,  9, 12, 14, 16, 18, 20])

In [67]:
y_data = torch.from_numpy(y_training)

In [68]:
y_data#依旧输出

tensor([ 1500,  3500,  7200, 11000, 12500, 18500, 22000, 24500, 28000, 30500])

In [69]:
x_test_data = torch.from_numpy(x_test)

In [70]:
x_test_data#依旧

tensor([ 3,  7, 13, 15, 19])

In [71]:
y_test_data = torch.from_numpy(y_test)

In [72]:
y_test_data# same

tensor([ 4400, 10000, 19500, 23500, 29000])

上面就是在准备数据，将正常的数组变成张量（有点像换形式）
then define model architecture

In [74]:
#define weights +biases 权重和偏差
weight = torch.tensor(numpy.random.randn())

In [75]:
weight

tensor(0.7722)

In [76]:
weight = torch.tensor(numpy.random.randn(),requires_grad = True)# open automatic gradient compute weight bias打开自动剃度计算关于权重和偏差

In [77]:
weight

tensor(2.4253, requires_grad=True)

In [78]:
bias = torch.tensor(numpy.random.randn(),requires_grad=True)#true开关

In [79]:
bias

tensor(0.4342, requires_grad=True)

In [80]:
print(weight,bias)
'''
print(weight)
print(bias)'''

tensor(2.4253, requires_grad=True) tensor(0.4342, requires_grad=True)


every Tensor has a flag(标志）‘require_grad' increase efficiency 
grain exclusion of subgraphs from gradient compute允许从梯度计算中细粒度地排除子图
如果单个操作的打单个输入需要渐变 gradient ，那么output also gradient渐变
反之亦然不变-不变；performed 执行 所有tensors 不需要gradient 的子图中，never backward comput 向后计算。

In [83]:
#define model
#Hypothesis 假设 = W * X + b(linear model)
def linearRegression(x):
  return x * weight + bias

In [86]:
#generate(create) predictions(gass) + compare grounnd truth labels
#randomly initialise weight +bias ---> model can't predict properly (right) at the moment
predictions = linearRegression(x_data) #x_training的tensor

In [90]:
print(predictions)

tensor([ 2.8595,  5.2848, 12.5607, 19.8366, 22.2619, 29.5378, 34.3884, 39.2390,
        44.0896, 48.9402], grad_fn=<AddBackward0>)


In [88]:
print(y_data)  #y_data = y_training 
'''
为什么不是呢？那正确的是什么呢？what's the correct answer？
'''

tensor([ 1500,  3500,  7200, 11000, 12500, 18500, 22000, 24500, 28000, 30500])


loss function [先导入数据+改tensor +定函数线回归 + 定损失

In [91]:
#loss --> use [MSE] mean squared error 均方误差（那应该还有别的）
def mse(x1,x2):
  diff = x1 - x2
  return torch.sum(diff*diff)/diff.numel() #numel 元素个数(12345)->5
  

In [95]:
#comput loss  ** lower better
loss = mse(predictions, y_data)  #预测和y训练
print(loss)

'''
PyTorch会自动计算损耗的梯度/导数（关于此处的权重和偏差）
gradient/derivative
weight and bias
想要 automatically compute need 设置 set 'requires_grad = True' 这个话就像开关
call 调用 backward()  trigger 触发 automatical compute gradients on chain rule（基于链规则的梯度自动计算）

tensor(3.4731e+08, grad_fn=<DivBackward0>)


In [96]:
#就是计算梯度：compute gradients
loss.backward()

In [97]:
loss

tensor(3.4731e+08, grad_fn=<DivBackward0>)

In [98]:
# after backward (倒推法？倒退)向后传递后, store gradients in tensors(involved 相关) ' .grad ' property性能属性 
print(weight)

tensor(2.4253, requires_grad=True)


In [99]:
print(weight.grad)#重量梯度

tensor(-455465.7188)


In [100]:
print()

In [101]:
# gradient for bias 梯度偏差
print(bias)
print(bias.grad)

tensor(0.4342, requires_grad=True)
tensor(-31788.2012)


adjust weight + bias use gradients 调参 用梯度
reset gradients before next forward pass(向前通过) because PyTorch accumulates gradients(累积梯度/渐变）

In [110]:
'''
don't want update operation though gradient
in '【torch.no_grad()】' don't automatic gradient (stop)【requires_grad = True】（start）
le-5 == learning rate （this part)
'''
with torch.no_grad():
  weight -= weight.grad * 1e-5 # 重量梯度  【a *=2(乘以 a=a*2)】 [weight = weight -weight.grad * 1e-5]【Wnew = Wold -lr * Loss'/w'】
  bias -= bias * 1e-5  # next reset the gradients (don't forget) #是一e－5
  weight.grad.zero_()
  bias.grad.zero_()
print(weight)
print(bias)


tensor(6.9800, requires_grad=True)
tensor(0.4342, requires_grad=True)


In [106]:
weight

tensor(6.9800, requires_grad=True)

In [107]:
bias

tensor(0.4342, requires_grad=True)

In [109]:
bias

tensor(0.4342, requires_grad=True)

In [112]:
print(weight.grad, bias.grad)


tensor(0.) tensor(0.)


In [116]:
# predict + compute loss again  这回loss will lower (weights +biases)  【变成了重量梯度？'】
predictions = linearRegression(x_data)
loss = mse(predictions, y_data)
print(predictions)
print(y_data)
print(loss)   #3.4731e+08, 低了点

tensor([  7.4141,  14.3941,  35.3340,  56.2738,  63.2538,  84.1936,  98.1536,
        112.1135, 126.0734, 140.0333], grad_fn=<AddBackward0>)
tensor([ 1500,  3500,  7200, 11000, 12500, 18500, 22000, 24500, 28000, 30500])
tensor(3.4524e+08, grad_fn=<DivBackward0>)


multiple epochs 【多时期】（循环起来）loop